SELECT E.DEPTNO , D.DNAME , EMPNO , ENAME , SAL 
	FROM EMP e INNER JOIN DEPT d ON E.DEPTNO = D.DEPTNO 
	WHERE SAL > 2000
	ORDER BY DEPTNO ;

SELECT E.DEPTNO , D.DNAME ,  ROUND(AVG(E.SAL),0) AS AVG_SAL , MAX(E.SAL) AS MAX_SAL , MIN(E.SAL) AS MIN_SAL , COUNT(*) AS CNT  
	FROM EMP e  INNER JOIN DEPT d ON E.DEPTNO = D.DEPTNO 
	GROUP BY E.DEPTNO, D.DNAME
	ORDER BY E.DEPTNO ;

SELECT E.DEPTNO , D.DNAME , EMPNO , ENAME , JOB, SAL 
	FROM EMP e  INNER JOIN DEPT d ON E.DEPTNO = D.DEPTNO 
	ORDER BY E.DEPTNO , D.DNAME 

-----------------------------------------------------------------------
